---
- Developer:
    - GitHub:
        - abbr: GH
          icon: github
          href: https://github.com/
    - Stack Overflow:
        - abbr: SO
          icon: stackoverflow
          href: https://stackoverflow.com/
    - Docker Hub:
        - abbr: DH
          icon: docker
          href: https://hub.docker.com/

- Social:
    - Reddit:
        - abbr: RE
          icon: reddit
          href: https://reddit.com/r/selfhosted
    - Twitter / X:
        - abbr: X
          icon: x
          href: https://x.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          icon: youtube
          href: https://youtube.com/
    - Twitch:
        - abbr: TW
          icon: twitch
          href: https://twitch.tv/

- Resources:
    - Selfhosted Wiki:
        - abbr: SH
          icon: mdi-book-open-variant
          href: https://wiki.selfhosted.show/
    - Awesome Selfhosted:
        - abbr: AS
          icon: mdi-star
          href: https://awesome-selfhosted.net/
