---
- datetime:
    text_size: l
    format:
        dateStyle: long
        timeStyle: short
        hour12: true

- search:
    provider: google
    target: _blank

- resources:
    cpu: true
    memory: true
    disk:
      - /
      - /pendrive
    cputemp: true
    uptime: true
    refresh: 3000

- openmeteo:
    label: Delhi
    latitude: 28.6139
    longitude: 77.209
    timezone: Asia/Kolkata
    units: metric
    cache: 15