services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "${LOCALSTACK_HOSTNAME:-127.0.0.1}:${LOCALSTACK_PORT:-4566}:4566"            # LocalStack Gateway
      - "${LOCALSTACK_HOSTNAME:-127.0.0.1}:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      # Try auth token for cloud UI (may not work with community)
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-}
      - LOCALSTACK_WEB_UI=${LOCALSTACK_WEB_UI:-0}
      # AWS Configuration for easier client setup
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      # Performance optimizations
      - LOCALSTACK_HOST=${LOCALSTACK_HOSTNAME:-localhost}
      - EDGE_PORT=${LOCALSTACK_PORT:-4566}
      # Community-specific settings
      - PERSISTENCE=${PERSISTENCE:-0}  # Limited persistence in community
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'

networks:
  default:
    name: localstack-network
    driver: bridge