apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashdot
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dashdot.home.ijlalahmad.dev`)
      kind: Rule
      services:
        - name: dashdot
          port: 8120
  tls:
    secretName: wildcard-home-ijlalahmad-dev-tls
