apiVersion: v1
kind: Namespace
metadata:
  name: dashboard-network
  labels:
    category: dashboard-network
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    category: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: downloads
  labels:
    category: downloads
---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    category: media
---
apiVersion: v1
kind: Namespace
metadata:
  name: file-management
  labels:
    category: file-management
---
apiVersion: v1
kind: Namespace
metadata:
  name: automation
  labels:
    category: automation
---
apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    category: databases
---
apiVersion: v1
kind: Namespace
metadata:
  name: git
  labels:
    category: git
