---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: databases
spec:
  encryptedData:
    REDIS_PASSWORD: AgCsLUPNtJkjgj8Y3Cop2GFnKl0igZ1v6WRdDD/iAwSZ3g5ry+SpDVo5S81CpbcJwhjpPwTlxft1//0kSZ1ophk/zGCQ+66jERetVxxFoBL7t6qsMDWmcd0BnluX2SZapvnjpwdumfnptcEAMNzLsBIN4vBwVfrbMD1c94anQfOj8ce6ivQ9k3/QPtA0oopJztPU+1viPxn+Mh4H7pZnDnXNd6Xt//MeFgVCyfwb8NAgsZK1HaCYSAfaWGuWbopfad3s7beJu8NESYv5V2jZVqXTlOQEEfEP/MKZCBQxLU4X67xXESJrEG9hG87PEWBikLzfpDHo42MLgpSS79Zm8S6Is5oEeLU4gXF2B+N60Wq3o/h8CqW0W82Y1sHU35R3zmoMzRs0RQvYjGAPv/yfJfXCZ7Z6EWI0b4CKPQoDG2p1LwkTYRxrUepMTdc0DCFjBCicJfWlDl2cjqAGsQ0+6MgrWZI95iN7L8s1gcOFEIQit2/Bs14KzimQTno/OWtVQik+jMx7W9juuWNLK99dNClH8/dP8GZqXitQQ5OEG9oI9gE1Avns6KwPsphBPMoOocTOk7L3bm5HxBh/1g5L0rHSDYx2N4VVgHKsbmzW3anqzYQBPmr7RmmoqhlFybXu1/EMS6JSwW6VgSkOPbOt9VkpM4kCFBLDSQYW3GFJNpou5kAEfMdvp1GvGtODy/tLlO53AgRAMVF01g==
  template:
    metadata:
      name: redis-secret
      namespace: databases
    type: Opaque
