---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: databases
spec:
  encryptedData: {}
  template:
    metadata:
      name: redis-secret
      namespace: databases
    type: Opaque
