apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/pi/pendrive/k3s-data/jellyfin/config
    type: DirectoryOrCreate
  claimRef:
    name: jellyfin-config
    namespace: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: jellyfin-config
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/pi/pendrive/k3s-data/jellyfin/cache
    type: DirectoryOrCreate
  claimRef:
    name: jellyfin-cache
    namespace: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: jellyfin-cache
  resources:
    requests:
      storage: 5Gi
