apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/pi/pendrive/k3s-data/home-assistant/config
    type: DirectoryOrCreate
  claimRef:
    name: home-assistant-config
    namespace: automation
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: home-assistant-config
  resources:
    requests:
      storage: 2Gi
