apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bitcomet
  namespace: dashboard-network
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bitcomet.home.ijlalahmad.dev`)
      kind: Rule
      services:
        - name: bitcomet
          port: 8700
  tls:
    secretName: wildcard-home-ijlalahmad-dev-tls
