---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bitcomet-secret
  namespace: dashboard-network
spec:
  encryptedData:
    WEBUI_PASSWORD: AgBfl1CzJzUbzsBM+k0x7FGbokrbyC0iwPHiTXkXUyGHJJiDqLbf8WwZVxfmuFHbj9Gtja1zZ66rypU8iTU9y2Ol3A+o9UXdwlHLQPfIRXNDCsOaVj3oyC09NPoc4PIp6CX8GmQbszG7O7/lOwsSoZyO0s7HMY2khnsVPs9XdYsTTbZcq7BiHUqhgnpw6vH8SXgltH78nbPPhvcGXBhgQGNNDswgCZOPO6sIzZTuW1TAr2IKrLUZG6/dZNBfZmtciiGi6uLG8jKotn9SyfHmczFWNmFJSmaSC3qSfEGb0u6tLIPRKqewtJAudZM3CnvYSyIBUThnQwMtTL5+HAjVM+DXoX74iu7hJqtRA7jhyNqm61hwYnSheSpLQA2zNu+ND/LQ7g1F4MRFZHa2pUsTFHh4N+jSyYzi+97xzSYkD83Zpnvj/9I3CAEoaX/zQH20+HJnsO5KepeMfORsOgfofMAt8qZtpyT/afk8ihcONghs4rP9Bwc54E08Sb7qHrgCK+pAigRMEqVocx5JWLo5YL4eY77KJLH7/lgVumaZnorgVK+uO7UJHzympZbpegdmf1js9a94yxsajmHH47sHCeYJp2gCNlqrlqF8kVQXHOpZ/Pga1cz7jI8sT8gUgCZJLJovP15Hw9JybedkXRLv6LdfvRDxUJaeaTzOYfL1aIVxNgkRecsiT9DSMSefc4JrIWLeuWf02w==
    WEBUI_USERNAME: AgCU0Vspb0Vh61N/0/6MZs4izd6cWXHDWzFy4p15bhGUGq4l7D8cD63+Dx8kP69UWgqBrx/ybn944o96r9GOxYRzcs/QYRBlbT+4/SllqsZOdVvIXgiYRKm8rJMTBEbK7YHObkZSjNdXbnJ6Ajguie7bMx2mRs/gE8rWI+cEUakKJDT/H+uc/0nNUFuktFNhdeopzYfNRe240P/YoVFVK/eHEsZZDeOd2/9VCssDhCxf6xr0iWYgxZqr8CEaH0hzmvjZadEo4mlH+reTh2pY4wqC8i9H0tfX9KxYIyQdQmKXbQ/jY/4RciZmJkSMhgmusrrt9pE14+peBTZC/0x0KsNT4t/SOWn9VR3PVh/B9zA9Pw9ne7umy40I946ZGvQBQKBQafNj6DvgHy31SHCnWyogt/tjIcChyN3kuIcpJcf6nLnwwWQmvUOaXqj+EeOnHf+C7bkscOizUrStIRcZlYXCUW56eSgTgqMFWztJmf6qeL1efs//I2PXOAVSGYqRvvzySDzIV5U5dcJe7eozi8Jqps9/wXs3H7C10i1qGD7+o28x+ei9qAuQWuhwNDQKYupjtSmLC/kwrp6VBfScWCt2XC2AzNTk5qn6Oz+uFbQqs1cd+vRtCa93ZZqHeJmvDY7qFxgZvpjYHuElEzLnH7ilnpRROpSj75/VzzqNAXVx7EiM0G5q1wLFCKs0bFnlj8HD87+Tcw==
  template:
    metadata:
      name: bitcomet-secret
      namespace: dashboard-network
    type: Opaque
