---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bitcomet-secret
  namespace: downloads
spec:
  encryptedData:
    WEBUI_PASSWORD: AgAhHy+bReijMgbzCG8KBqFFp0Z8J96X4jEfM8L4gRxzUZ2RWz5uiKnNNBu6+NmSC3A4PzTjMhGF0y9Nm/7nXLKoQdp/8zZdWbIgEs/BPRZEPZIEVOYsIRiiUVWHDR66hdZga221IxRgQW+JOitlQ3vMPJRCkqB/COyw01Lr9GCZxNdH4mDrHI8YWkRlIbPaolIF2vYw2KI+hVYADbUvh3SKzsXQdnjOliXkPy4kF8PIwBao/OTDKrGCMLUmNHx4/YpmjtNCzpVkb7Oy072r4nJUKH/hko+7egDkdFTCe8GbV9R4KYx7YrEPkLpYYPI5Hcn8VjcwU8/uDyYGIP6R+pKPcHRFrrQ0HKkCngpz1kjEaIrVHrL3pciW7n0imY1fml9rF9/ifhsF5adD5CnxNOAWDCy49NQE542RdDc3fF+Bz8CIlgWQQTBP/EsIYNhoXhdvSFLMgssIVxxM6qWmqOZJpninyoY8zJ52BjGr8YrMtO4Lha4BPrOyN9b0z01adx6P6LMOlLBsgTswLVcbPE/U1gZUGNO49myUQ69R5nNhk4LB3dcs4YXN5F1C+15772OPcI6vwelcQ3tv7YSWg3YXmvwo6IuY/vi5NCuxrJ6frs4Ht27OiRy//Yj5oTs89SdXAbGGolvgVCbAfGInv7fUvPFPsDad6ceSIkQIpqR0WJx+tiquvaKzS+NvOzRfq+RSnhNrCA==
    WEBUI_USERNAME: AgAOU18uwQNPsP3JdoajAr2xc3rDdV2my0Nt8LclaQws9mvcWiZfciXzgWV31m6kuKOBvm4BSAaIsKcVmBzXKjVugRmf0fNOEOun6LYlcpQtVeM76eO/spDb15DvbbkRYubbyjma4dqHuvwmCiQ609rsQgbnspz3iRjLFx0RJrafWtl/evJb4QQdTJhbjJFYxVjpXo8U0X+IndM/XlqYPbBIDQv0lky7m82DRXlkR0b4HKmHIkqId7LzHa6xDj6ECFBKbAExKSn17rsbd86aXpGdHboiU+QSFlwAfVMCkaETxlhfmuf+kEwPI2zZh/prTrCRadH+Svu0jAhu2CvWb83/Xe+1U8hL5TjOWPhgoqPBZJG6d6p8lBnL9d7/IOkgW/3O8kVRX1DuqbOnPSPP8cQZECVf1ih3KeZ7SXg84tKWyBakjDRUdlzauaTZcq+04dIX8xE+kgSX8dtyV9FNbkuqe3VUo0G/FXQu0n0O03+gQXBqkwwYBqFcszXgAfy52UfC4FuuS1dW68RXretSn9TOnAfYj0P/L6gEDXZRJuvgxKSMYDZmKag/JbkBQY+O30uN9gl69a4FAsolzi9YSS2Ah93QwAFkjw4aDqlDsn5kom0qMMoH24Jt/IF4b94QVzjQ/5gF6eosQCrWz4ofmhMJvutLJlQV1lldcQqeHl7NKq8rQFjEd0paWDVB8KFbTuSJ/BFWXQ==
  template:
    metadata:
      name: bitcomet-secret
      namespace: downloads
