apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/pi/pendrive/k3s-data/portainer/data
    type: DirectoryOrCreate
  claimRef:
    name: portainer-data
    namespace: monitoring
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: portainer-data
  resources:
    requests:
      storage: 1Gi
