apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - sealedsecret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: homepage-config
    files:
      - config/bookmarks.yaml
      - config/custom.css
      - config/custom.js
      - config/docker.yaml
      - config/kubernetes.yaml
      - config/proxmox.yaml
      - config/services.yaml
      - config/settings.yaml
      - config/widgets.yaml
  - name: homepage-widgets
    files:
      - widgets/mini-chart.html
