apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/pi/pendrive/k3s-data/n8n/data
    type: DirectoryOrCreate
  claimRef:
    name: n8n-data
    namespace: automation
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: n8n-data
  resources:
    requests:
      storage: 5Gi
