---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: automation
spec:
  encryptedData:
    N8N_DB_PASSWORD: AgBbAOGiI2IwWaE8N0uH4EsHs6bw8TCmTvDnhXbWmSaojCZammK2XUTwLOkHKwIZhypiYv0/E3jGqoXHGTJ/9k0PJhVylZVAp8gSCwpSELlEeBAgAYCDEdPEIP5NhHxtuTgGj6NXLWw1r4xA2d0nZu8JaaFiRSU1eLm3M1k9j0SBlsg0WkX1tNaMEBa145e5hOlba+px2o+ufsbJyY/ekCMAl7ga6uudc0zEcNxShusjLd6ESUu+9h6yuRUkrmSVAHq1LtBMnoNjpfb2ae9LrKwsHKo/WeDmatDlnVTajtdtoSHC4NbETOtYmQ3Rt2EP0n6CujdjGXXkz07HsAY+pzqc9Z6ssqcm6WVXaM39A63FgGI+d4nftw4oGgD2eWgr8S+f23oudzu4cvOrGs6kYPMnepoF0MiOXmCxzh7paqJqtBb0TH9f1oabj64YNoJ2mlzYF+VZ+tmB2gklzsmHcLcuGiEWrX+w6l5uwWrZEyT6U1tfmeCdrdy1L7e6mgMCxVGsAsi0bSROHWCBF1P23aWFMHxSuCAUt6mawtLhWJ/ATHyThpqKlbUXqyuhjZ4dKNck4wIpG9WOaxku/4XH4F97P1sZN8KCnaAsPgrSaeL6USVn3LmA/303ywRy4/yeIa/OYyzxJSY/FoUPnMWfMYnaYVLJsTwWv6ZhTymD5HwSBHskBgkvdrQzL1hx236DVefa3EP7c5EqeOBqxy1LsBgV7pM=
    N8N_ENCRYPTION_KEY: AgAwLtc573UwhevbJ5B4jq9vwoh48x0UJrhHt5GYJdkP70DsU/gsikCR/uuCs72Ex3rTNia7g22ABUo7YaKEnV90M4h7WzsO7wsiS22KDeK49yP79JcYkcjCsQbEA5eGuZ0aZrzFu/bAmBVS25vUaIzuyXDR/6ueaGWRw5U51oUQLDpxttHS2vyuiceK4nIk9P8yemVjRRqsUS30fkrMfDxwl/nMN636gTkvWVRMkcfEvl9PTUpnPCyXiWmKkuT1XtXFBpS+VLmg/122hu5NtQ6rbeKtAHRVcQhjUHhpeKyhlaxQq8ZaxhcdSZ4nvHijLCzP21uHoZ0167B7I40kI/0gMhXGA1Qvip3xaVeH/uh8U5A+lt+YfwCeJ5EJoa/fHJ1P8ly531Z6XI1fmUpoS6ixl+DX5dx43c5cUIt93D+Au00GLg+gRVcBlHJIsiX/k0NF0W5XC1d4P8Bh7maytE1/QYGxSFmqU/22OsBXjarZtAsEtp0PvpbtMolgfbdVsO8Hj6rMoGrjROvCDgMehONqcmUzbubN5Fd5FABGCT0h3C0ZrvXkcbTFmqw7vC6GKECg89volGDhOr9MICnwRgSxV88iVdp3U/woM/yn3njbaBRSRzkVtN+BwIJ1e17kdb6J5oe/j/YAL1qdGWgjzG0ckK4v0v/fkxCSMU6rfVOuFUG+caEV4GfaIx4dKOEvqcvOQRID5hSdlcyEZyoP1sriPjAkdbp8oS7yrIrY6iL8FpPI9md87U5bv4t0YWNPJgXqPU7wrdJ2e++ZJTdCa+lq
  template:
    metadata:
      name: n8n-secret
      namespace: automation
