---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: automation
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgCdrori2BO02RjY3pNTod43EhnbdTURP86fXoK1IUgfyDwyrwnC5B5xwQfaAnQ2phY285j4Z1ey1BOkMsdOKEkzoLd1C5Xe2GIH5J6EDtjf9btcSFfeab1KwbCo1Mfob6IpFW0VwJrnunp8PttnL712bCxN5y5t4/1jJefhwQjt0JCJ1TSZygM0NdM06ck6CAIkjZeg5eznGq38529Gul/wHZywHW+NoG4JUEDeJkmdgOf9xh4vR/a7wENrAG4WTV8qUPbCKYrHCIDbAxOfJH2xnzKtJcFAunmtCTkB5YaLUxoSN/8KmqItx9z24CXvUlSQNJB0UD0y0HDSwgWJsHfTavcG+ZM5LCy83uRVwoa7BQ+3bGFKcFA9lQgz1OapaXTEal6Hoaojz9ZdQ82p9qWTSPC8tMi4Fi2yjxVZopzf34/0t4Johzn/eFmyHCuP4bdZuPnfPsKlytPnnYkJcsdC0XU3kDM89OjA2onglqIHFrJwhtBM5FuoSLumeZrd6ArTfo3bNcIZaA1PFGpoOzhiLfJcDwQeO9nNCX/HDqcihd4beo2w7aptlJ8g001jyb54/HRKWhPMxTxs7vA5Ccyep10P3Pf24CPp+U2wMq5Q9bm8FuthZpdHf5Ti/oZmvNVYDOdSC2MtOb/o6X4T3+ZGsPxBZxa0b6rOGWNnoZfIPs7llgNDSAFEpa0KR+ZXS5s5tfly0JBFMwL2HqQudg8/sR3NL+qpy+P+mSa8XlzDEfyB0CQzK4/BYk4J8gywyezZmByobR0nH8vG+VYx7c+B
  template:
    metadata:
      name: n8n-secret
      namespace: automation
    type: Opaque
