---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: automation
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgCdrori2BO02RjY3pNTod43EhnbdTURP86fXoK1IUgfyDwyrwnC5B5xwQfaAnQ2phY285j4Z1ey1BOkMsdOKEkzoLd1C5Xe2GIH5J6EDtjf9btcSFfeab1KwbCo1Mfob6IpFW0VwJrnunp8PttnL712bCxN5y5t4/1jJefhwQjt0JCJ1TSZygM0NdM06ck6CAIkjZeg5eznGq38529Gul/wHZywHW+NoG4JUEDeJkmdgOf9xh4vR/a7wENrAG4WTV8qUPbCKYrHCIDbAxOfJH2xnzKtJcFAunmtCTkB5YaLUxoSN/8KmqItx9z24CXvUlSQNJB0UD0y0HDSwgWJsHfTavcG+ZM5LCy83uRVwoa7BQ+3bGFKcFA9lQgz1OapaXTEal6Hoaojz9ZdQ82p9qWTSPC8tMi4Fi2yjxVZopzf34/0t4Johzn/eFmyHCuP4bdZuPnfPsKlytPnnYkJcsdC0XU3kDM89OjA2onglqIHFrJwhtBM5FuoSLumeZrd6ArTfo3bNcIZaA1PFGpoOzhiLfJcDwQeO9nNCX/HDqcihd4beo2w7aptlJ8g001jyb54/HRKWhPMxTxs7vA5Ccyep10P3Pf24CPp+U2wMq5Q9bm8FuthZpdHf5Ti/oZmvNVYDOdSC2MtOb/o6X4T3+ZGsPxBZxa0b6rOGWNnoZfIPs7llgNDSAFEpa0KR+ZXS5s5tfly0JBFMwL2HqQudg8/sR3NL+qpy+P+mSa8XlzDEfyB0CQzK4/BYk4J8gywyezZmByobR0nH8vG+VYx7c+B
    N8N_DB_PASSWORD: AgB7bsnbgW2YeShK0dZLq3dKtfQ0dd/lagkZS9iuCC7dFd3t83xxnOJjp7qPLkR5M8mM1+TMR0clXgPE3W6w0/y1160NlTmkqwOs+5nmvsSvXeL0TVVs06nNWe5GWdldHAG7vx8XO2sbVMEQGRkTum/5bRcB10XvL5gIyIJ7DbRmYXo0N+NXkQVvPBeGuH1jA6rtPsx0/dWBBRs+OG27+y5uwZsbVXd/yAS+/wLzGVmqfDXtP4IRqjESiV4g83j1U/ALRYd+uf0xkU2xtMDwt9iwPSlV7K0tfOAeUL2Ef7495kdMzKrZgC1ytKy1dt8UI6MORZ8woRE/m/CKoM2cZSXblk4EOonyXmWCNt8m+NQpGuqb7mFsGh6cGj4SMuYE2pUneJ4AK+biO6SOWRb1MdMNFcf11Ip38lPA+knoY2WjbPMoYB05vxsBnt0roXGTgz5HHBbNeYUAXSakv5dx5NXC6cO9cNis2A5hI6mzvje4yZgp6dzPIX04y+VpliP/u5zLPmCN+4x0a9rO99S3ajPv7DcMfUxVcySjNrK5D9qnpWFPPNJ/TNETXzpvkWisQxg0KYzlhAG7sQzUxCdt04ZRh+qbtYGmZBuq2ckK8hsOcckD6DdeU+zbHAwGeAT/w9JWHrDhYdNhymXR7domdPnt+LMstb44v23BPx6X7FG4BTrZWPM0R6G9xX7cN5bDj4YZK5doXEPPouF8ggfxcyFP3Lk=
  template:
    metadata:
      name: n8n-secret
      namespace: automation
    type: Opaque
