---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-secret
  namespace: git
spec:
  encryptedData:
    FORGEJO_RUNNER_REGISTRATION_TOKEN: AgAy1F+QZlI6RO1KVJL+SfGZ5Fb5y5YykqnYZcOeSExYt39tI9H7Rk5GrP7zqoWrjKWZ6TtRr3FlXhwIGqB7pW3UeFqM7HG6omFoZqySahDVyeZAB1ChitN63Z03255+GKQRPXPI1LkzuJhpoIl/xeUo0HrsfInf+AV8yuBX46ym0lO28yq7Ep7QUA+CUHXyRb9OQsf914cceI3L4VN04DKzhDjMJ73g/SvgtB/pyXQrzO1vhbDQPYGvP4NH8iqJCeKVhwYm9ZcW+lCmKDV5cVAU05juTc+IKnF5y0VAms58l03yfDd2dbsoWL7ClRXWHvJlHzLTn1JKF5ZQ7tuMQwkhldUHVUyIz1KuI/rOryJ57LDK44q15HRrexYOMn5A/0PHMryCSYwfAJuJ2EcLfDcS/p2WRmJvofiUxWFJGEgm0gjCHbm1DCkAIAJd8bX9/Bb7E5kum/S+CvdAiw1zdt2PBUJiYEJF+ND0Zihzapt/xpRqlAwfyOg+h7iTBpemn4lhIXwIwT0FfUuYvJ3E0f9O6eObhc0xeFzEEU9cEOhaOguUlzkgUVBS7d8j+LeHyytiN3eaAsl9gW71U88meZcDd+A/+aXjbZgLlQg8Q1Wlwctq55mvmvmqFNYfRpJalSBdAzF7ZnXyJb6uG2a80qMz7A7GrcsovQ6f+orCFXtfqIFrKKFMI4HfrRH09H7Yj8n09gDr5wN4o2WzuUhV7RiQbCWBLZFl+jaiJXN97pOV1EQtbyTtDXE9
  template:
    metadata:
      name: forgejo-runner-secret
      namespace: git
    type: Opaque
