services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    env_file: .env
    environment:
      SERVERIP: "${PIHOLE_IP}"
      PIHOLE_DNS_: "${DNS1};${DNS2}"
      DNSMASQ_LISTENING: "all"
      VIRTUAL_HOST: "pihole.lan"
      FTLCONF_LOCAL_IPV4: "${PIHOLE_IP}"
      FTLCONF_dns_listeningMode: "ALL"
      REV_SERVER: "true"
      REV_SERVER_DOMAIN: "local"
      REV_SERVER_TARGET: "${ROUTER_IP}"
      REV_SERVER_CIDR: "${NETWORK_CIDR}"
      PIHOLE_UID: 1000
      PIHOLE_GID: 1000
    ports:
      - "53:53/tcp"      # Pi-hole DNS over TCP
      - "53:53/udp"      # Pi-hole DNS over UDP  
      - "8080:80/tcp"      # Pi-hole web interface on port 8080
      # If HTTPS is needed later, expose it after enabling inside Pi-hole
      # - "8443:443/tcp"     # (Optional) Pi-hole HTTPS on port 8443
    volumes:
      - ./pihole-data:/etc/pihole
      - ./dnsmasq-data:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - "${DNS1}"
      - "${DNS2}"
