---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: databases
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAm10fFEoKymP/7A58qTSbSrBfoA3vnwYibFwutwGBK9p/COFAtW1Wcet5eBmpxwztX6QbrabNPFCkXTns0MfrXEuCoKIl0+pNzKZSL6yoZial+iy9pL96PfHDkPB45oroyH6eZRlQegclLJsOocOwPxPMfrVePr5SnEjYNT4ffaNT7WA9Tf2b30YWeMGw6CX9n2Q95BqEs+AovhpDuQ27+Xd8nGuGaKyAejMSgnCVffcvbL4mg9cutT007mpiCIBTED5GGIr85JOgrbtzIky9Ap3dYeMlJDk3phHWKL97TJCGkt49BknkLDsoUYNJF6AWOfTI6NWgBXDAke83qYtEndV2I3PJ6hqjZwjAx4g9O1BTqNvbLmjYdU6tFt+9+O5tA+SwkQcE4gipXTfMZrD4CxhBZNpPXxWp0scnjDm6H/hAImS/mwY5nlG7TxdiwOy/JmtCfCk5gmYfrchhbkdecFva0lyKKlN0HkMSxQ16yBWmmDx8XMF21baixzRNJBEVgWPbe6FbHtahdbAFCWOVrnGaMzRGfv/Ymtq76uO7CgkvrfkxUTubAYndtbT+SWGcdWs5CWG2RfYUeO7QZ0AgQep1zSr0sNZ0yTnQ+5G1Nar8kLagF3QMY++flRgvnhL2drGatcR6q6FrKtX3tlCQBpPOby8LRECBlv/5BNGb8UNq1Evc7oWsI07Hfks/K0heIwOxT0FvdYlBT7TH37boRQQ==
  template:
    metadata:
      name: postgres-secret
      namespace: databases
    type: Opaque
