---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secret
  namespace: security
spec:
  encryptedData:
    PUSH_INSTALLATION_ID: AgApwTRQfCrgANMm3Tu68yak0q7xw3kqfNK6LDTsUmJE+m7IRESlldVcuaiyagPGHgYEayOLDT12W6g6zLY+Vi18WwuhETabwRjzEDArn/gW6gzNnBHeMLosuHxuL9YoXX9u6nRzC6uSnx2cOrko438RzZLgFoT0ZDyfPm27S0xdBP82ivhliRku4UrW02DBDoHY17zdEN5iVlb6bP2JizXgz186wh+4ICuAgSybz+vfu+w3oXPybPHphiahj5nirffUOa19f/wE3Xh/ZuWc5rX7iFHHnkd0jHRaiBwk3E0u8xii3qSKSc+samthDV7LjSF8m/zVDxRzPw7SO5TImNw462AcjDZdgX9DpeXjp+tU8yrLXN1HzJmSKQuMOCD1JQ1kVHs6iGqFY4APcRNV3KFZ81jg01NSEAbJiD1dAeMPyMk2v6Zj2tkpV2kwnATslfS3FL0UgD5Ah5WneR5M6BPIL3/aHJ4LfVIkSyBFhu5mEtiIqAyO2pUSJiYmrnLaYazCjklCY9y7Ln+UXpPYzVJRHHuHodHrYvj6VNs/wpT7vkbHbTq5IsKk5n2LshLSyNR2G63mE+AZH1R6fcua3QlFHpvnCb3WpbUEBCpaFpI1h7nwbccbbuC8F0Hm5Eq5PJWjUUVWpVjAGrtKnG3FORL5G3/zYCu+pwX9XU/ZkKJPOLOLyqNb9eSAiDGfH5ReGJ2vgV6CEP38Ak/gYL22le/zGx7W8jvs316rfAW1uSQ9d3Lgczg=
    PUSH_INSTALLATION_KEY: AgAThzq0DR8iKyMonM8vwiMok3Xr/774QqIlGqNgoQgQastBUdlAxAgOifPnIvfdzxos1dUV4z/KltyW3M5hCsVe7THVtCa1F1J18IpfZKdRsFSdK06TF05JRov6OgkLPxi6MonP8tStUUVqnJnkEtNDboqKc9UFTNlZkhrB/gN20+mQVRSD4max2qkgU6TpGVjUUofXKomwNrzA9Pf3gNaATGveoOFlIGM5Dw9sSUKhH6/poJId4RXSLODuM9IfeRLbreeoDzV+13M3XowU5zIh8S+vEh2isOZxC/YyHC8ATSY3wbVU+ptfCfXLKvRupZPiyr8hzFxf+lyDE9P2SdzYSJMV49uTJCDSnJF7qv/KypD29H/5+J72nc1K/a1gRSAVqyd90Z77VjCZwAda02f85x5HYPLHc4CFLHzlIZNFmaSs+Py3Z7mno1pbbcOfxyydRd3dIdAK4tw2CE01Rns4/yd0OqIMEncEsA13NR6RYZbHhYWibU+8ikzO/47wu3TBrmZIJXtCdje9zlJAN6vK7xYq6subDpa7XE59sN+/P38hhAd8CFz4AYLnOYgRn7jRUwn8UeH9C0GgPC4fo/jy0ZMVVaKfdbxcO8QIGNAWJ55LuHw8/77/aOcFS4FHNFNSxBr7Zy2/brfVOfuo+vx2gOZttQtW8wicPMJUndeWj70UDL3yjSH89NstduKxDuFUSyqDPw/sRkujqhDlNvk/04jPew==
  template:
    metadata:
      name: vaultwarden-secret
      namespace: security
    type: Opaque
