---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-secret
  namespace: databases
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgB3Hzd0mdXsKJGkU9ycp3LE69jNNisJb2SyNgL6HZwvOr/aqw6lAvEkTwdXdY2ePZyKC1Z/8DkePSlPM4PM9ISpslsNxyipNR27PVevnEL/7IAdQBurG0LcDQILwn1hbhetgqc5hD9Slb1pdhEa2oh/mmkvZyWMqEuAm7jiTYeT61WOzbVCAvEAePhLnhstN+2H2y39rtL7ecra3kNFFM+EW4dQXoqo7fEpjCWw/s8PTnTP9cBHiGBS6eL4V2oxI6EEkSSt97yH/HN9A/NRyevkxWHagPl3mtwafNmF+Vn3hk1woBC4tytV7uYolHs4T1HrbRzGfXtuz25QK7Q/iJBzz+t0e4VRQmqz0RCFWT6Wdbu96V6cyBXmwVtiFP4SEmUqtKkC5ZuaVfWWIJ8b8cJhbS/EHvAqU6E0KrA3cUkSDop4UNQjUU8z1ocPq5j6L8+ZIHsyoK6gP/vkex+Wbfeh8howN+vxCSfpFohzk5asUf9W09e1IaNsT+6VoNskLxhi68hzbIU5s1DMhVweVBWQF/ZknJ6l4eoy+60Gode1jaUnY6tykGVhkTva0auHkosPSJl4JuKrc7HFvhJlTOvdEMVbR1MFKRr5Pzwbga64NGGf8DjK/qpYmQ0CnkcBN9grzGcNUzV5p/CShgcZSUQ7/aGzRQfiD3Udriv3mrfiKQcvt7mvtGwOGVt8tbxHCsOrm41mTRNuJo2aimh9OQ==
    MONGO_INITDB_ROOT_USERNAME: AgBCrRtAlzGGgNwUT5q3Ur9eKih071KhtUW0pWnieCt7mnbqhPoSl9vitsPe4s+85aQS1N1clh/9AnNAVqaJHJvLI2rl4gomOpqCYJb6ftjY1c3WJiCx9E50nUD1HQ50MCLMeaJ9VU7lHSUqhz2Wgsf61IH1znARYaWUAvGGi6EE1ys5L7xEPqaBbt27sVxC9zLSnWkkZWnSysudGLDcFewzN9V54cqp4WhrrDnM8ziGMIaFi0IxpSXQsPXTw+GNkMspakOZIvmtK4RAUyQSp1lK7uq6ZNFDGGLcTQ/aqB6ff7Y2iQb341pc1iKyY8wPItsGp79F11HLKxHRr6eOXKxxm7XoyTNrUObV8q2CaikdD4JJMUYxBKvJble4lxjugGAz2WTdLFI5SHo50A2wonkhKV4BZSdSg/0bbxKGIjyzWfQl0Uibw7VnvG+Z8kPBfaGoSbF02s6VU23gvN3PU/fq0aPEGi2dolhh2jqSCGrUCvDl70/W2sMFBXCZwlFFJykvF4YjMYj9EFJ9C/HskJqmGx96oR5c6X1ZZEToYHtCyoolkfXTYsbFSwtLJqlb9r/KifYx5co4YoRNePGOJrHySvxs5P1Bqb0zv7rGQv13AbCzm3gfUpiMWc7+kMb8Eqmtg+62oakXxzHI6nP783WNMYdTgPjibLbSK3tnBZx0Dn+vwhUBYCcJJBSssEHJfnSrz572aQ==
  template:
    metadata:
      name: mongodb-secret
      namespace: databases
    type: Opaque
