---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backrest-secret
  namespace: monitoring
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAFlsVS8gHNMItOB8wnDuj/crf5KWcZ00RUpNOZIql+BlCDvqXv2lCysh6R7V3KHS8cGCSb16AGMHmGv/IgfDTzYpHcMaNBiroX/05ywdXDjuZJqk4UNSLwIn/LHueAPmx4CD3SfWSDE99vrIlSM/vML+WTNvZfwMCVGd1wu1n70FcqK5aHYND3ic1iraW6MzDha2KI8bkbjFE734XiF12onbZpVhi2mDKjkoiQEP27Ebkz3PSW8S/gSItOtVQnvUWcp1bzu+9DKsMQEZwiSfYPFKsmGXiwqcejrdAQzGNk9LIMta/L5VK/LnTocZhPUmTtOJ74BLdBuabujocoCSi4g+Gv7O0QH7YwhwkhNkMsjcxGMtE8KdewYpRRmlNVcF/02rmdaoPzwqduRF5wNWf5gb6VJfCIaQqBL92PVeQulmj7w1WMSwsPNmv/UvFNwy72XI2J9jRtGEnw3YqzxMUuTN6/zTc/scnUhI5M20ZtQLiVEbkX5i9J/hX5HhUnzmcerU7WDslCMmst9DeDco8g6AR29T3F7ATqJ3uBVX8XHWZlO09afkxtQ32nYYU9qy0Fr8aMWLs40hvmANd6cz8YxStXawexxmDlyH4P9atys1ZLCosszQ7RK81hcKP2Jred6yOp72r8eP8PIJ/TONKs/OOSg7VyhjBtBMeeD0B4UMKrRFpFGolPlEoEiblYN2sV94P0ln1r1khbboLZ12bRLzSJVw==
    AWS_SECRET_ACCESS_KEY: AgCgrIup+iUIIle6DvNh9wLKUcT14Z8bv6X8Llw/CGRp3Cu3BcxJDtFTCQ0Vgh5y7It9+0Wk54bDld0CjUWV/wsK8Fe4BVYhELzyjWxlk/nyxLFz5S9wIzwPbQfnGn43xgjt8cSXyEnKVaP+kCHBta0mPJfRqDPr1DrreTMfo60mHY5RM7YXAuL4omNq0ufV0xGdoqguerz54Nc8fZSraXhvwc0J98IuSp8YQlUNgpcOkMzPv/pxl9MNSDxvKxGgaeFgZpBj1hEFfGXaWPt7C+mtUBoPvitW1N5XmDHGnbVpQh99XNm0FBbQsPrpwB9uU0YdG9ZHXu2IhAU6DByYdUSAIwLvIb3Ceo9fZcp//5UvAdIPaAjVgoB3wqxhQ1prJUFzpZv9CSLuVPPSBpQ3oXhO/szFP1rt+nJb049nVZ+UleTE2Yqo/4te/C5Luz7VN/0+aANwL940a9yfLvbkxUFfGuOOXtfsngte+gvJBaoFCy+kmdlYIE7q1nUZQJI5smVNQMcMskWUWophYkU+MrSTwXNPs/k+wHVehARSO9+4EL98AsPD+vwYc+4kLSi5pDXUjv5U+2Nf6p/uEPdlQypC16iUEDvI/IZNJfB368xKtP6/FKOJUCR4Q7cLUF4wVuQznf0OfLXU2T7JfgW8DEB+IQDyd6uh9R/hhxZhy4xtYiV+GUfsCOfRT0iM+9r8xrxyWvzusZdzNrF0xEbTaBJl3YavLCxlNmhB1Pit1x7HOuFKWVXKbdAU
  template:
    metadata:
      name: backrest-secret
      namespace: monitoring
    type: Opaque
