apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: databases
data:
  03-mysql-tuning.cnf: |
    [mysqld]
    # Memory tuning for Raspberry Pi 5
    innodb_buffer_pool_size         = 128M
    innodb_log_buffer_size          = 8M
    innodb_redo_log_capacity        = 64M
    max_connections                 = 50
    thread_cache_size               = 8
    table_open_cache                = 256
    performance_schema              = OFF
    skip-name-resolve
    # Disable SSL cert auto-generation (not needed inside k8s cluster)
    auto_generate_certs             = OFF
    skip_ssl                        = ON
