---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-secret
  namespace: databases
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgC5C+PIwCp5KJFmkaivCeRqSR+m+/9bsknt5tGbA2XurQidmhx/Bm7DNc48vQFLHpanbNLXaDfEuLt5jVbJOP/UaWDuYihxpwddM7FSONHClLvCNZDMai4H5CZiew+UTWYkcIPJMFGX/k50SWeHgXnh67gxaOM+2DnjJGt8j6Bbopeg9oeHFJc2aHzckh2VNApr/kjijug7NFQSU7FjN9R+y0HiRLMqkjyOPwnjeU/qOHtCDCeCeU1BiGW//x/LwANZncYRMwrbg/X0lkCxVq2OEIUwbY1BApKnqJ/XV3FquL5xJmfTvessF9RRI9uxDsZW1GFoSzzq/05+ODnXzH+JGhvLhy5hoTJk5B7dU4RhU6qTQyZQUivYq3+dcT0pcgWmtnT3a8sdTeQnuAIcAeu/tQ7Uqmj/xdLlFA9PkbK9mxoDkeaUORTg56Zvspj2Phb/aIM0D78GwdJDoTly6w/RSVjQtB+zpDH3o3drmjKowXvsrGg55pNUFF21Wl/mnxdshdDZ2PA9aIEI97hCwsHhNM7pkWswZ9KYkxIx307SC3Pgy6q6vi++t/1BM5VSYGn7z9wb+VDxf+IHKUey7OpI7PJtTQVMW+kuGLliPby4V/NTNkTGwm0PcjP3GZOu6QMivkgXdrwtnrPnxUeuykmKnBbCjDM8Vjs4e6AwaExXSI85sNky+U1qbvlO/I6yrn3eJdOsKp3OiXJNKQTq3g==
  template:
    metadata:
      name: mysql-secret
      namespace: databases
    type: Opaque
