apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filebrowser
  namespace: file-management
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`files.home.ijlalahmad.dev`)
      kind: Rule
      services:
        - name: filebrowser
          port: 8300
  tls:
    secretName: wildcard-home-ijlalahmad-dev-tls
