apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-config
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/pi/k3s-volumes/apps/filebrowser/config
    type: DirectoryOrCreate
  claimRef:
    name: filebrowser-config
    namespace: file-management
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config
  namespace: file-management
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: filebrowser-config
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-database
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/pi/k3s-volumes/apps/filebrowser/database
    type: DirectoryOrCreate
  claimRef:
    name: filebrowser-database
    namespace: file-management
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-database
  namespace: file-management
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: filebrowser-database
  resources:
    requests:
      storage: 100Mi
