services:
  portainer:
    image: portainer/portainer-ce:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-portainer}
    restart: ${RESTART_POLICY:-unless-stopped}
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer_data:/data
    ports:
      - "${PORTAINER_PORT:-9000}:9000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      # - 8000:8000  # Remove if you do not intend to use Edge Agents

networks:
  default:
    name: portainer_network