apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: aria2
  namespace: downloads
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`aria2.home.ijlalahmad.dev`)
      kind: Rule
      services:
        - name: aria2
          port: 8080
  tls:
    secretName: wildcard-home-ijlalahmad-dev-tls
