apiVersion: v1
kind: PersistentVolume
metadata:
  name: aria2-downloads
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/pi/pendrive/downloads
    type: DirectoryOrCreate
  claimRef:
    name: aria2-downloads
    namespace: downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aria2-downloads
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: aria2-downloads
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aria2-config
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/pi/k3s-volumes/apps/aria2/config
    type: DirectoryOrCreate
  claimRef:
    name: aria2-config
    namespace: downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aria2-config
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: aria2-config
  resources:
    requests:
      storage: 100Mi
