---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aria2-secret
  namespace: downloads
spec:
  encryptedData:
    RPC_SECRET: AgCnoqZV4KlrLdKXq4AXMFNfqMSXn8cYrFqE7dzm2mbf5+zYfOK2fjFizz8ExMnpEQTjbrqoOmbN27luPzqOgWoqTFBl4iSRWVubjgnSw2FxbYiXelYEQ2TRs9oKHvnsW5jefXwSJBsflXs1h7QULBt/fBLZqrGvFWabiXvoEIJfdV4Gz9omXLwktqBVo24aIGBw2crWq2ZDduwzw6bKRHOS6G/89hcfi5ei6xCFLy3xxEIebPQBj8HQ0pKpvW3VK9R/b0mYgNd7gDFwNlaoRBEIaVV4Bk0/wr7O/Ok3yTtZvU0B1C3gH9txT0wjJkbm4D9vsrbqr4j6Hkd23F92Z5kQVmLNLGnZAKUzkivaqMvMGy6EATnonke98AuC5otMS9FYo2Dj0qsO6oL0CQIuDEk7Rml8MSoiwTbn3+1ik2/aZ2L5W4Nm0PlLCXv8HJBgUvHGWqhzvSyuCcPXSIp+iwwN00jRtaM9UMHxWCpdtKXfAAbaNKoY6h0xwAI75VQSJi649sy8Ta0D5mGniwVHEl7g38Vq/97JVBx5XiufWgbqTmmCwjeDh2LDWWtqbEvVtUrknpdtDwVQwzEx6HjJ7ClEuOMA9UDtaXcxILvWuoT5CF97qPPBJpj/ITcgwFNcupwOVByemWi9w+N6EcgbQOe8z/bmdK44HerXIbcYIQVirCmv/DiJvzShxFefWG8eEPlP70FzuAmMkx+bCJwPCmyA/qtdfla2aEtmUS40XqcKpA==
  template:
    metadata:
      name: aria2-secret
      namespace: downloads
    type: Opaque
