apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/pi/k3s-volumes/apps/pihole/config
    type: DirectoryOrCreate
  claimRef:
    name: pihole-config
    namespace: dashboard-network
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config
  namespace: dashboard-network
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pihole-config
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dnsmasq
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/pi/k3s-volumes/apps/pihole/dnsmasq
    type: DirectoryOrCreate
  claimRef:
    name: pihole-dnsmasq
    namespace: dashboard-network
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq
  namespace: dashboard-network
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pihole-dnsmasq
  resources:
    requests:
      storage: 100Mi
