---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secret
  namespace: dashboard-network
spec:
  encryptedData:
    WEBPASSWORD: AgBlA7gV6Wkejmn7yLrFO6mtZpfokS3ZUl5d40FPy1HN7iKo5L2viK6Rklj+0uR03iyFRQx10uViqf3dQRFbecp22b+e0k/mq9GqIrAGpM3At5Kpo9OMZ9RYFw0/pDyqnf+QZo3BIxVlCUR2Q0IY18AOhQ6ZJciKZTpIV2fFWhjhw6tbluRCiIE9coJUAqd90b0N0m+r9mth3ncRoMNZ7/lIJ1robsY8WHuGhja+/dpWzkRJscWPEYkLnnukb8ZXRpLo3WmTUhR4+0glgXEF4pWH+fI7CC4CqLY+VrKscD1p3pzBuV6eb/EJEhbrpwoEUIM/FAbyezhD8ejQwlKdD6qfMzIHXfgWGvZrSYmZdjtwi8+d5reEFDSV5bBqlhrpqr1h5gFN2QVmwcF3eQzM3ArVMknyk716vKwBBdbeci1GY/ORSEbMNpKTxLOYTCXs3ZpowodlOAiheol8Uhf4VoST8kw8UT/dOjNQqijNwYQDS/ljqjk6xfcYoA8/bQhDVNyxvV0WM0TtzW8a4UOySxNsDm2YeE7rp5UWjBbio84PokluxcY1EvDSu0HGIb1CUTTwMA+FqROZNck5XbyH2QIolaAyBB5WSHs+LTrmbORFV97bjCCKpnCitxoR70c4SYi+yJjuYCurUUXK/v+efeB2QEihYAhhFKrFP0x1FwF2BO03qq5EXJ7rHIfemN6S4gNSGddz77zwbA==
  template:
    metadata:
      name: pihole-secret
      namespace: dashboard-network
    type: Opaque
