apiVersion: v1
kind: PersistentVolume
metadata:
  name: homarr-appdata
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/pi/pendrive/k3s-data/homarr/appdata
    type: DirectoryOrCreate
  claimRef:
    name: homarr-appdata
    namespace: dashboard-network
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-appdata
  namespace: dashboard-network
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: homarr-appdata
  resources:
    requests:
      storage: 1Gi
