---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homarr-secret
  namespace: dashboard-network
spec:
  encryptedData:
    SECRET_ENCRYPTION_KEY: AgC1QBq3LZHIF3sX/qQlgJMQuKiHC1uHbhJyo6oAeKK93fKBRK2ncc0p0HbGWguZmUs74XO+lAZVyb7QmknEOYCzxIpUtQ/wgixbUuR8lOL1OnJLV9NCxZiCuXNMVK/eM0kIux84CSsgq2aZFnWntwnlv6DO/sof5Br5D0sKrXrYz3Apoc7NraORQ5G5R71XoMQxuAvRj0ALPVAsp66cS/VsrNy7bLBm7ZHThaguvsDKkLtOQWNE6kBjNd7xPCMitSH5DPjkxTUb9xfPMC9dzNbjIHN2FibT0GPWgdx4weukdmiOy0lkI7eif4dk38YwNyy0DfWc/A3oyku+oGUoE7qGI9issMQnV58UFBvxb2bI1J6xt6KiG0pBG7UQiUuUokINv5tKh6+dOZY0+sz/G2FBW07vyt2+g1Vkj+7811Bo9Kdt+5TN/ZWIANvgHlZ7msqqKzm1HsiIWmBPvxtOBeN0KWWtlyYiKhwobvY2mWWcmVysipoeDYsQwSnwi8mvqJIsP1daviaKnwqvE5Cn+p6lcbxNoS4eBf3Pc5ct10dREcsjaB24JUgGk0cW21p6JbWesZY7PyCJZmx4rZk8OCvwT7H5OeDmrcTAXWBxkagl8S40AoFHDSOSTq953Ww1+J6jZqOWPD4EsrlHuCfrOea5zML7eEJS6uuWXku8iBGhv5mhj9cGImToi8wIP9KuYQLR3V8IDnfM2dDCbplA/MqClXjHxfwfPY4JtYOnz3WYFRoMCrYMyWN+EnvUifPv8T3O6QKZZS7dfHHCkKH6qhWM
  template:
    metadata:
      name: homarr-secret
      namespace: dashboard-network
    type: Opaque
