---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homarr-secret
  namespace: dashboard-network
spec:
  encryptedData:
    SECRET_ENCRYPTION_KEY: AgCSbRfgnRipyOgOiF4Gyn6SZaAiaNgYWx1kFi9TIcb1Jw23gSZt3UsNc3R2uUpkRp1YDWjhb9YvmiCyh+SbqExPU9q9rtGMajHFyfp5kVXjFB1V8FV2UoN24YK1YiyDJOIDaXt/GS+HNPkK8nsgBWaNVO2IoWy+hwLvp5FGqOXDf31IwkeIuJuAZaoQCGIjKAwlgIZi2Y870deOWtsiKs+FMmzjp25WbaKBjV93MYfVotTVHmY4/OZtuncsGOiaDv30T5geQ5M9xhtexq7w9v7INPFmr+6XrxO4H39uaT1Ijl+avx0ZE3mo48soNLpuewZ1BZCOjA1oRudtGGbLPjA7Zi5S4/1x/ve+s3gKnEw6iIMXVBjD+h96S2x5S/M0gY91pyiAYdIU9O9eVcy2K8HZ+CspoHJ8G//RH1CjoSx2ekMjvFg8Br7ERgF33Q0ylaw23BkrCOm6YXXtNHb8GegxT2bTjiTX9pgx6hosTTo2m8tZmkyX/dt9Fc3uD/f1ZpYp7jOrDhWA5e/gPSSZggEtWL+gXvshrdwpZ8R1s7bln/calS3mtoej+rIk6g2MFMpGEvv6vSS2J9GXig/+0LmzD79DEkVCdlaVv1c4kGKrfHiJC5W7e5calGIZDGVeHQwRnWQBxy/aa6PGdYO8d5I6VttjwvTvoQzAooKnj2wENe7+eRElZ7+w9HNodrHYHcV/UNwqLnF9usuV5ZPZLZk+kYXf7qPcHbUma4/Bn8YvRAztb6c67l0lahKFZRyJyLhKDc8EIVJxl6tYh3vyzq+r
  template:
    metadata:
      name: homarr-secret
      namespace: dashboard-network
    type: Opaque
