apiVersion: apps/v1
kind: Deployment
metadata:
  name: twingate
  namespace: network
  labels:
    app: twingate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twingate
  template:
    metadata:
      labels:
        app: twingate
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: twingate
          image: twingate/connector:1
          env:
            - name: TWINGATE_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twingate-credentials
                  key: access-token
            - name: TWINGATE_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twingate-credentials
                  key: refresh-token
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
