---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAGKlj40Ey7HCa/coI7Ay7jrshS7/D2ELSwDfIa0RvFf28kuVeFWkOXtjuAhSi2VxnYMnAoqk28pMp6gTpauExW1Sk9/WA9oRIDhuxquhn5GdkyoMr67Owt8eRcvlsZCzwCHKvXTlqg/IUWgZ6qlXR3lnLakptya+oy106gDGa4wln4mkpmYUBrHbjEgGharp+ZZfGXpA3Uh8Xic93jYqiRfF4dGru4h+/vNA6iJnz71M/aQkNj+XeS2YQXRIvpipvoH9N8r42d6Ot7/XCyX9sxWyIdGv/zycqr3GfIRmHxTxK9uh0+27uGvqeilJUFaLgiGuHw6LboDgMza56VvObi8ldx4e8s1ZRBNPPuy6yWp3pe5N8wj/mzk30GRWc/3Tnh6unVQ3cDxGCz5arIYKs6xAlDPoCt8eSngGGmoqA4UWWa/1EqGsLJkRw82FGpNIlzlysFZTmngcr9YhPqvBHPqfZWhWQdFawrawa+zgPGwsh2kOeaJESg7hR/QQZvecpdMaew3J0WwICJjsSokTUM4PvrDMZETaDx2oZjIOPcnPqZqi+Xe5LhxwT5NBEWQ+xvSFYHYVXVYxF2tCUSO6HIXdeaM9lRmR7x4ry8ICrRCb7NR49lbI7as/scqv8woirNVSR3sSM949nmezlUK40TU2DOo+vw4lyQ4EGPIZFJAAEQaAPFJfkHRpfdD9tpc6mqDo1z3T4LOPpkPKgVocFqv29ivnDF5nBmufrxl+cxUrLHy52qUtW10/hDVfXFdq7vmsAwyA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
