apiVersion: v1
kind: PersistentVolume
metadata:
  name: samba-private
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/pi/k3s-volumes/apps/samba/private
    type: DirectoryOrCreate
  claimRef:
    name: samba-private
    namespace: file-management
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-private
  namespace: file-management
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: samba-private
  resources:
    requests:
      storage: 100Mi
