---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: samba-secret
  namespace: file-management
spec:
  encryptedData:
    SAMBA_PASS: AgAFhYcWBM6URF5iDRiVdTfcdz85XZXjByvIrKEhjhi9v+tKeq75P4ZlGttRuvHYHPWG0P2++FCFVM4+hEfPbP6C7yTmes/NlFKftDcp/P+/Oj6EVToKs5MvA7PQFgFvXoqa1ONNClOCHmhGoFr/wIgAta4wOdX2z1TXx4GUrtskOGVJawztRkr/UaRp86CA/srsXAvWMCobBqBeJMbH21SO+hZazvEspRu69rw1MqHWZPAMEMczMmuLKCOz+FnP/V6C5EGoOTTLEGveVLVBSzwqq3HE+J7M/LRol3qI2XE/KzQ7q6yrqML+/Pc+4CMZvIGRzU66ZyAVtgbDI8H1INA02UJKAqiLbMc6hCrtWxK4XmQ4z5LCgFVBCgXenBUD0FMCmmDVll6KMhvIxbPHov4LBmE0s17ZD80H+uy0kE2LjMdcN7MOJDA8Fm/x7wHt+bTfFRk/zobvRpm2fvtoYgcvlAajaIRmjyDcH+1oG1HF8tOiWGUR/U8m11cqsNyWdUomiFN/W1pNdpTK5u+aglmlXPVY+UKOafJmqZDx3sNjATBTJVRPtr4GbIbi4RC2qBXJ3QutyiID1eNM/WCFQlBuTlp7c/8+JYQa0URHND/tkLCBVuNLdc35AxuGGDqpMtOGtr3O4plVcmQchEiF3UmGAy5DfMhkRozLHSlS/NItAdDlDrlMdyf7e3SQfWNNPvL9rWSORsEA3xHC
  template:
    metadata:
      name: samba-secret
      namespace: file-management
    type: Opaque
